### ISSUE TITLE
Work with eslint 6.

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/eslint-plugin-svelte3#18]
Just for subscriptions.

You can edit this first message as you want.

Thanks.

**Comment by Conduitry** [comment]
I've just release 2.0.0, which should support 6. There are a number of differences in how the plugin gets configured though - some are a result of ESLint 6 change, some are just cleanup that I took this opportunity to make, since I was already making some breaking changes. Make sure you take a look at the changelog and readme.
